akhq:
  server:
    listeners: "0.0.0.0:8080"

  connections:
    default:
      properties:
        bootstrap.servers: "kafka-1:9093"

  security:
    enabled: true
    basic:
      username: "admin"
      password: "password" 

  logging:
    level: "INFO"

  queue:
    consumer:
      executor:
        thread-pool-size: 100
      queue-size: 10000
